config/routes.rb
Rails.application.routes.draw do

devise_for :users
root 'pages#home'
get 'kitchen', to: 'kitchens#index'
get 'livingroom', to: 'livingrooms#index'
get 'bathroom', to: 'bathrooms#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bathrooms_controller.rb
class BathroomsController < ApplicationController
  def index

  end
end

app/controllers/kitchens_controller.rb
class KitchensController < ApplicationController
  def index
  end
end

app/controllers/livingrooms_controller.rb
class LivingroomsController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    authenticate_user!
  end

  def kitchen
  end

  def livingroom
  end

  def bathroom
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bathrooms/index.html.erb
<h1 class="bathroom-title">This is the bathroom page</h1>

<div class="home-link">
  <%= link_to 'Home', root_path %>
</div>

app/views/kitchens/index.html.erb
<div class="container" style="background-image: url('kitchen.jpg');">  
  <div class="kitchen">
    <h1 class="kitchen-title">This is the kitchen page</h1>
      <div class="home-link">
        <%= link_to 'Home', root_path %>
      </div>
  </div>
</div>


<div id="wrapper">
  <div id="columns">
    <div class="item">
      <img src="http://www.covertfurniture.com/wp-content/uploads/2015/09/Bookcase-24-Inch.jpg">
      <p>"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque.</p>
    </div>

    <div class="item">
      <img src="http://www.covertfurniture.com/wp-content/uploads/2015/09/Chest5-194x300.jpg">
      <p>"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia.</p>
    </div>

    <div class="item">
      <img src="http://www.covertfurniture.com/wp-content/uploads/2015/09/MagRackMain-150x150.jpg">
      <p>"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia.</p>
    </div>

    <div class="item">
      <img src="http://www.covertfurniture.com/wp-content/uploads/2017/03/FS-Mag-Rack-10.jpg">
      <p>"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia.</p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MtnValleyWoodworks</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Rubik+Mono+One" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/livingrooms/index.html.erb
<h1 class="livingroom-title">This is the livingroom page</h1>

<div class="home-link">
  <%= link_to 'Home', root_path %>
</div>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
  
  <head>
    <title>Mountain Valley Woodwork</title>
   <link rel="stylesheet" type="text/css" href="CSS/styles.css">
  </head>


<body>
<div class="container">
  <div class="app-card-container" style="background-color: rgba(35, 35, 38, 0.9);">
    <div class="card">
      <div id="content">
        <div id="wrapper">
          <div id="title">Mountain Valley Woodworks</div>
          <hr>
          <h3 id="subtitle">Check out our Furniture</h3>

          <div id="buttons">
            <span class="btn btn-primary"><%= link_to 'KITCHEN', kitchen_path %></span>
            <span class="btn btn-primary"><%= link_to 'LIVINGROOM', livingroom_path %></span>
            <span class="btn btn-primary"><%= link_to 'BATHROOM', bathroom_path %></span>
          </div>
        </div>
      </div>

      <div id="map">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3072.7509922940553!2d-111.44148108447486!3d39.63281017946392!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x874c3f3d2588dc9f%3A0x26b6da7ab24506fd!2s150+W+300+N+St%2C+Fairview%2C+UT+84629!5e0!3m2!1sen!2sus!4v1486165363084" width="400" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
      </div>
    </div>
  </div>
</div>

  <div class="covert-logo-div">
    <a href="www.covertfurniture.com"><img src="http://www.covertfurniture.com/wp-content/uploads/2015/09/CF-Logo-No-Text1.png" class="covert-logo"></a>

    <p>Check out our sister company Covert Furniture</p>
  </div>

  <%= render 'shared/foot_links' %>



  
</body>
</html>

app/views/shared/_foot_links.html.erb
<div id="footer">
  <div id="footer-nav-links">
    <a class="foot-links" href="#">MVW &copy; 2017</a>
    <a class="foot-links" href="#">PRIVACY & LEGAL</a>
    <a class="foot-links" href="#">CONTACT</a>
  </div>
</div>